include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Enable helpful const-related rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    unnecessary_const: true

    # Optional: Enable this to enforce using `final` where possible
    prefer_final_locals: true
    prefer_final_parameters: true
